parameters:
- name: "serviceName"
  type: string
- name: "environment"
  type: string
- name: "imageTag"
  type: string
  default: 'latest'

jobs:
  - deployment: UpdateGitOps
    displayName: "Update GitOps Repo (image tag)"
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              persistCredentials: true
              clean: true

            - task: Bash@3
              displayName: Update GitOps Repo
              inputs:
                targetType: inline
                script: |
                  git config --global user.email "santosh.mohapatra25@gmail.com"
                  git config --global user.name "Santosh Mohapatra"
                  git clone https://github.com/santosh-gh/k8s-20-deployment.git
                  cd k8s-19-deployment       
                  
                  # Update env values file (YQ preferred, but sed works if format is stable)        
                  sed -i 's/\(tag:\s*\).*/\1$(imageTag)/' multi-helmchart/$(serviceName)/${{parameters.environment}}-values.yaml            

                  git add .
                  git commit -m "Updated $(serviceName) with Tag: $(imageTag)"
                  git push https://$(GITHUB-PAT)@github.com/santosh-gh/k8s-20-deployment.git HEAD:main